# Development 
version: '3.8'

services:
  db:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
    # stateful data even when the container is shutdown
    volumes:
      - db-data-test:/var/lib/postgresql/data

volumes:
  db-data-test:
