name: Deploy to production

on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Authenticate with Digital Ocean
        run: echo ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} | doctl auth init --context production

      - name: SSH into Digital Ocean server and run app
        run: |
          doctl compute ssh --context production \
            --ssh-private-key-path "${{ secrets.DO_SERVER_PRIVATE_KEY }}" \
            --ssh-user "${{ secrets.DO_SERVER_USERNAME }}" \
            "${{ secrets.DO_SERVER_HOST }}" -- 'cd /root/libsys && ./production_build.sh'
